### PR TITLE
Fix #350 - Strip styled components referenced in css by not used in the render

### LINKED ISSUE #350: Styled components referenced in css by not used in the render should be stripped
So I originally thought this issue was related to the renaming of child components but after some digging, I noticed this was due to some logic in our button component that would leave some styled-components completely unrendered. These components however are referenced in the css of the parent component. Since these children are never in the final dom tree, jest-styled-components cannot get their class names, but because they are referenced in the css of the parent component, they show up in the final css.

Here's a reproduction case:

```
const BlueText = styled.div`
  color: blue;
`;
const RedText = styled.div`
  color: red;
`;

const FancyText = styled.div`
  font-size: 16px;

  ${BlueText} {
    text-align: right;
  }
  ${RedText} {
    text-align: center;
  }
`;

const component = (
  <FancyText>
    <BlueText>A container that has styles for an unused child</BlueText>
  </FancyText>
);
```

And here's the snap:

```
.c2 {
  color: blue;
}

.c0 {
  font-size: 16px;
}

.c0 .c1 {
  text-align: right;
}

.c0 .sc-fzXfLX {
  text-align: center;
}

<div
  className="c0"
>
  <div
    className="c1 c2"
  >
    A container that has styles for an unused child
  </div>
</div>
```

As you can see we have a rule referenced for `sc-fzXfLX`. The issue here is that if the hash changes this will cause the snapshot to fail erroneously.

During this process, I've created a PR to fix this issue here.

### PR DESCRIPTION
**Pull request by robert-hurst-cmd**
This PR removes CSS rules referencing unused styled components from the snapshot. See #350 for details.

The approach I took here was adding a filter for CSS rules which contain references to unknown styled component class names.

Note that this also fixes a test; "referring to other components", which was incorrectly passing, as it contained a reference to a container element that was never used.

### CODE REVIEW

File: src/styleSheetSerializer.js [hunk 1]
```diff
@@ -96,6 +96,9 @@ const stripUnreferencedClassNames = (result, classNames) =>
     classNames
       .reduce((acc, className) => acc.replace(new RegExp(`${className}\\s?`,'g'), ''), result);
 
+const stripUnusedStyledComponentRules = result =>
+  result.replace(/[^\n\r]*\.sc-[\w\d]{4,8}\s*{[^}]+}[\n\r]+/, '')
```
Comment (robert-hurst-cmd) [inline src/styleSheetSerializer.js:100]: Not sure why, but during testing, the styled component id's length ranged between 5 and 6 chars. To be safe I set this to between 4 and 8, but it might be good to dial this in to the actual min and max length of a styled component id.

File: src/styleSheetSerializer.js [hunk 2]
```diff
@@ -96,6 +96,9 @@ const stripUnreferencedClassNames = (result, classNames) =>
     classNames
       .reduce((acc, className) => acc.replace(new RegExp(`${className}\\s?`,'g'), ''), result);
 
+const stripUnusedStyledComponentRules = result =>
+  result.replace(/[^\n\r]*\.(?:[\w\d_]+-)?sc-[\w\d]{4,8}\s*{[^}]+}[\n\r]+/, '')
```
Comment (robert-hurst-cmd) [inline src/styleSheetSerializer.js:100]: During testing, the styled component id's length ranged between 5 and 6 chars. To be safe I set this to between 4 and 8, but it might be good to dial this into the actual min and max length of a styled component id.

This regex matches all CSS declarations that use selectors containing styled component class names and the trailing whitespace before the next rule, or html. When this function runs all styled component class names should be replaced already, so anything else found at this point should likely be removed.

Here's a detailed explanation of the regex:
```
/[^\n\r]*\.(?:[\w\d_]+-)?sc-[\w\d]{4,8}\s*{[^}]+}[\n\r]+/
 ^      ^ ^             ^^                      ^^-----^   | grabs the trailing whitespace after the rule
 ^      ^ ^             ^^----------------------^
 ^      ^ ^-------------^   |  grabs the styled component id with sc- prefix
 ^------^    | deals with babel-styled-components prefixes
    | grabs the start of the selector
```

Comment (robert-hurst-cmd) [reply src/styleSheetSerializer.js]: Though this method works (provided the selector is always generated one one line) it felt a bit fragile, so I've pushed a different approach where I filter to roles instead.

**Comment by robert-hurst-cmd** [comment]
@probablyup any thoughts on this? I'm happy to adopt this as you deem necessary.

**Comment by robert-hurst-cmd** [comment]
@MicheleBertoli Let me know what you think once you're able to check this one out. Any changes needed, I'm happy to make them.

**Comment by jjaybrown** [comment]
Any update, this change would resolve our issue with jest introducing unnecessary css

**Comment by mattclough1** [comment]
@probablyup any chance we can merge this? This would clear up some CI frustrations for us

**Review by probablyup — APPROVED** [review]
Thank you!
