### PR TITLE
Fix toHaveStyleRule support classes with displayName prefix

### LINKED ISSUE #290: toHaveStyleRule does not work with babel-plugin-styled-components
When using the latest version alongside `babel-plugin-styled-components`, the `toHaveStyleRule` matcher always fails (`"No style rules found on passed Component"`).

This issue seems to have been caused by this commit: https://github.com/styled-components/jest-styled-components/commit/8c2ea4a0a8789e11707e7f18e76b811e0d70c4c0#diff-4eed74593d3d8efde6a0959c9c35119bR71

Specifically, this line assumes classnames will have a `sc-` prefix which is not present:
```js
const staticClassNames = classNames.filter(x => x.startsWith("sc-"));
```

(similar issue to #285)

### PR DESCRIPTION
**Pull request by vxcamiloxv**
Fixes `toHaveStyleRule` support for classes with a `displayName` prefix from  babel-plugin-styled-components

Closes #290 #294

### CODE REVIEW

**Comment by vepor** [comment]
@probablyup any chance to look on this, please 🙏? It blocks us in updating `styled-components` as we don't have any other legit solution 😞

File: src/toHaveStyleRule.js [hunk 1]
```diff
@@ -68,7 +68,7 @@ const getModifiedClassName = (className, staticClassName, modifier = "") => {
 };
 
 const hasClassNames = (classNames, selectors, options) => {
-  const staticClassNames = classNames.filter(x => x.startsWith("sc-"));
+  const staticClassNames = classNames.filter(x => /^(\w+-)?sc-\w+/.test(x));
```
Comment (probablyup) [inline src/toHaveStyleRule.js]: I don't think we want the `\w+` part at the end

Comment (vepor) [reply src/toHaveStyleRule.js:71]: cc @vxcamiloxv

Comment (vxcamiloxv) [reply src/toHaveStyleRule.js]: done https://github.com/styled-components/jest-styled-components/pull/302/commits/002ccc5373bdc021145555fd4d3b04a2612bc5bc cc @probablyup

**Comment by probablyup** [comment]
@vxcamiloxv Could you add a test or two? ty

**Comment by vxcamiloxv** [comment]
@probablyup sure
